baseURL = "https://example.com/"
languageCode = "en-us"
title = "A Hugo theme for creating Reveal.js presentations"
disableKinds = ["sitemap", "RSS"]
theme = "reveal-hugo"

# uncomment for browsing at file:///
# relativeURLs = true
# uglyURLs = true

[author]
name = "adam"

# currently only the unsafe mode for goldmark is supported
[markup.goldmark.renderer]
unsafe = true

# choose between Hugo compile-time or Highlight.js
# syntax highlighting for code inside of code fences
[markup.highlight]
codeFences = false  # use highlight.js
# codeFences = true  # use hugo highlighting at compile time

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
highlight_theme = "vs2015"
history = true
progress = false
theme="moon"
# theme="black"
# theme="white"
# theme="league"
# theme="beige"
# theme="sky"
# theme="night"
# theme="serif"
# theme="simple"
# theme="solarized"
#theme="blood"
